### ISSUE TITLE
Through the source code building project, the jade package appears to depend on the problem

### ISSUE THREAD

**Issue by SomeoneSometimes** [flankerhqd/JAADAS#10]
java版本1.8   scala版本2.11.4  gradle是刚下的最新版4.2.1
检查jade包的依赖情况如下：
![image](https://user-images.githubusercontent.com/20027984/31539130-3f35ecb6-b03a-11e7-9248-217c69cdb18f.png)
去对应目录下寻找发现的确没有相关的jar包

在构建指导中看到需要在根目录下运行gradle fatJar，尝试运行后出现如下错误
![image](https://user-images.githubusercontent.com/20027984/31539383-fe70837a-b03a-11e7-852f-53e0b36c15e2.png)
![image](https://user-images.githubusercontent.com/20027984/31539348-e3a91a70-b03a-11e7-8438-5c8b7badfc66.png)

刚学习java不久，在工程导入上没什么经验，谢谢！

**Comment by flankerhqd** [comment]
Hi:

For the first question this is intended behavior. These libraries are all generated library, built by gradle script. You can consult corresponding build.xml for more info. Currently for subproject like soot-infoflow-android, the gradle build file is just a wrapper for the original build.xml (Ant build file) by original Soot devs.

If you want to read the source of JAADAS in IDE, I recommend android studio with its `import gradle project` option. Or you can import the project *after* it has been successfully built once.

For the second question, the gradle version I tested is mainly 2.xx. I'm not sure if it still works on gradle 4.x, as gradle has a well-known bad reputation for breaking backward compatibility. You can try *./gradlew fatJar* (on Windows that will be *gradlew.bat fatJar*) to let gradlew automatically download and configure right gradle version (the one we have tested and coded in gradle-wrapper.properties, which is 2.13) for you.

Of course you will need a good internet connection to download those dependencies(you may even need a proxy since gradle repo URLs are blocked in some areas). 

Cheers.

**Comment by SomeoneSometimes** [comment]
Thanks!
I try `gradlew.bat fatJar` ,it works and generate the .jar file .There are some coding problems in the run so i find the corresponding file to delete the Chinese note.
There is another request, I am learning to use soot for malicious code analysis, which is the reason I read JADDAS, and finally I only found the soot project doc document can be used to learning Soot's API , but for beginners to read up feeling difficult, in particular, there are many APIs do not have any explanation, I would like to know how you learn soot API to write JADDAS?Thank you very much~~

**Comment by flankerhqd** [comment]
Hello:

Yes the major problem for Soot is the lack of documentation. I wrote some wiki notes at https://github.com/flankerhqd/JAADAS/wiki, hope it can provide some insights.

For my understanding of malware analysis, it evolves from naive API analysis to complex data flow, and Soot can help you at different layer. I suggest you to learn it from easy task to difficult ones.

For example, we can set the first task to scan for sensitive API usage, e.g. sendTextMessage, Notification etc using Soot API. These are mainly intra-procedure ones relating to Soot's Jimple and MethodBody representation. You can start with docs at https://github.com/Sable/soot/wiki/Fundamental-Soot-objects and https://www.sable.mcgill.ca/soot/tutorial/pldi03/tutorial.pdf. Our goal is to be familiar with Soot's IR API, and know how to distinguish/retrieve API information from Dex with Soot's API, and also the CallGraph API.

We can then start to do some more interesting thing: intra-procedure analysis with Soot, playing with control flow graph and fix point algorithm. You will be mainly dealing with Soot's FlowAnalysis framework. The reference documentation is usually www.brics.dk/SootGuide/sootsurvivorsguide.pdf, although in my experience you will have to do some experiments and debugging to really understand the fixpoint algorithm. JAADAS has some examples on these and you can find some info at the wiki. Not hard to understand though.

Finally the IFDS framework is the most difficult one, with a reference paper: dl.acm.org/citation.cfm?id=2259052. It's also a fixed point algorithm, but the main difference between implementing your own IFDS and intra-procedure FlowAnalysis is that:

- FlowAnalysis works on DataFacts, for each FlowAnalysis template you will implement the KILL, GEN, MERGE, FLOWTHROUGH functions provided by Soot which accepts DataFact as argument and returns/modifies DataFact. 
- IFDS/IDE works on transfer functions with CALL EDGE, RETURN EDGE, CALL-TO-RETURN EDGE and NORMAL EDGE. You still have to fill in the template provided by Soot, however the value returned is FlowFunction ( a function that works on DataFact, but not DataFact! ). You can by some means understand it as a `lambda`.

Soot have some example IFDS analysis like soot.jimple.toolkits.ide.exampleproblems.IFDSReachingDefinitions, which you can consult.

In the end I have to say that you need to be aware that static analysis cannot be perfect. Static program analysis is an NP-hard problem (halting problem) in computing theory and it will have false negatives/positives. Also industrial productions will have to make tradeoffs between precision and flexibility. Make your decisions and good luck coding.

**Comment by SomeoneSometimes** [comment]
Very grateful ! How to learn Soot has been troubled me for a long time, and now finally understand a general learning route, really helped me a lot.Maybe after I study, I can try to write some soot study notes.最后再次谢谢表哥啦~
